### ISSUE TITLE
empty ADragDropViewDelegate extension, why?

### ISSUE THREAD

**Issue by ghost** [cupnoodle/ADragDropView#6]
Hello! I am learning Swift and UIKit by examples on GitHub and I'd like to ask one thing: why `extension ADragDropViewDelegate{}` is empty? At the end of the file `ADragDropView.swift`
```
extension ADragDropViewDelegate {
    func dragDropView(_ dragDropView: ADragDropView, droppedFileWithURL  URL: URL) {
    }
    
    func dragDropView(_ dragDropView: ADragDropView, droppedFilesWithURLs URLs: [URL]) {
    }
}
```
Thanks!

**Comment by cupnoodle** [comment]
Hi Althai, good question!

I wrote an empty function for the extension to make the delegate method optional. It's like when you conform to UITableViewDelegate protocol, you don't have to implement the method **func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {** if you don't want to , this is what optional delegate method means. 

If I didn't put the empty implementation, after you conform to ADragDropViewDelegate, Xcode will force you to implement both of the methods. Which is similar to when you conform to UITableViewDataSource, Xcode will force you to implement **numberOfRowsInSection** and **cellForRowAt** methods.

Hope this explanation helps!

**Comment by ghost** [comment]
Wow, that was pretty clear! Thank you!
