### ISSUE TITLE
Looking for Drag Source code

### ISSUE THREAD

**Issue by benwiggy** [cupnoodle/ADragDropView#7]
Not really an issue: Thanks for your code. But I'm looking for example code to drag from a view to another app. 
I can't get my head around Apple's documentation, which seems to be outdated, and the examples I've seen are for Swift 3 or earlier and dont work anymore.

**Comment by cupnoodle** [comment]
Thanks!  I have found that since macOS Mojave 10.14, Apple is using FilePromise, they have a sample project and documentation here : https://developer.apple.com/documentation/appkit/documents_data_and_pasteboard/supporting_drag_and_drop_through_file_promises

Hope this can help!

**Comment by benwiggy** [comment]
Awesome. (Couldn't find that myself!) Thanks.
